volumes:
  beastz_redis_master_data:
    name: 'beastz_api__beastz_redis_master_data'
  beastz_redis_slave_data:
    name: 'beastz_api__beastz_redis_slave_data'
  beastz_postgres_data:
    name: 'beastz_api__beastz_postgres_data'
  beastz_api_data:
    name: 'beastz_api__beastz_api_data'

services:
  beastz-api:
    container_name: beastz-api
    build: ./
    ports:
      - '4000:4000'
    environment:
      DEBUG: ${DEBUG}
      PORT: ${PORT}
      PRISMA_ENGINE_PROTOCOL: ${PRISMA_ENGINE_PROTOCOL}
      MAX_FEEDBACK_PER_DAY_COUNT: ${MAX_FEEDBACK_PER_DAY_COUNT}
      FRONTEND_URL: ${FRONTEND_URL}
      FRONTEND_DOCUMENT_URL: ${FRONTEND_DOCUMENT_URL}
      BACKEND_URL: ${BACKEND_URL}
      ENABLE_SESSION_ACCESS_JWT_ENCRYPTION: ${ENABLE_SESSION_ACCESS_JWT_ENCRYPTION}
      ADMIN_BASIC_PASSWORD: ${ADMIN_BASIC_PASSWORD}
      ENABLE_MAIL_SANDBOX: ${ENABLE_MAIL_SANDBOX}
      MAIL_URL: ${MAIL_URL}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      COOKIE_SECRET: ${COOKIE_SECRET}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN}
      ACCESS_TOKEN_EXPIRATION_IN_SEC: ${ACCESS_TOKEN_EXPIRATION_IN_SEC}
      REFRESH_TOKEN_EXPIRATION_IN_SEC: ${REFRESH_TOKEN_EXPIRATION_IN_SEC}
      RECOVER_PASSWORD_REQUEST_TIMEOUT_IN_SEC: ${RECOVER_PASSWORD_REQUEST_TIMEOUT_IN_SEC}
      RESET_PASSWORD_REQUEST_TIMEOUT_IN_SEC: ${RESET_PASSWORD_REQUEST_TIMEOUT_IN_SEC}
      ACCOUNT_VERIFICATION_TOKEN_EXPIRATION_IN_SEC: ${ACCOUNT_VERIFICATION_TOKEN_EXPIRATION_IN_SEC}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      SESSION_JWT_ENCRYPTION_KEY: ${SESSION_JWT_ENCRYPTION_KEY}
      ACCOUNT_VERIFY_TOKEN_SECRET: ${ACCOUNT_VERIFY_TOKEN_SECRET}
      RECOVER_PASSWORD_TOKEN_SECRET: ${RECOVER_PASSWORD_TOKEN_SECRET}
      RESET_PASSWORD_TOKEN_SECRET: ${RESET_PASSWORD_TOKEN_SECRET}

      # important variables
      REDIS_URL: ${REDIS_URL}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_LOG_QUERY: ${DATABASE_LOG_QUERY}

    depends_on:
      - beastz-database
      - redis-master
      - redis-slave
    volumes:
      - beastz_api_data:/app/hub
      - beastz_api_data:/app/user-bin
      - beastz_api_data:/app/user-content
      - beastz_api_data:/app/user-upload
      - beastz_api_data:/app/user-deleted-forever

  beastz_postgres:
    image: postgres:14.5-alpine
    container_name: beastz_postgres
    ports:
      - 33001:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USERNAME} -d ${POSTGRES_DB}']
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 10s
    volumes:
      - beastz_postgres_data:/var/lib/postgresql/data

  beastz_redis_master:
    image: redis:7.4.0
    container_name: beastz_redis_master
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli -h beastz_redis_master -a $$REDIS_PASSWORD ping || exit 1']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 33002:6379
    volumes:
      - beastz_redis_master_data:/data

  beastz_redis_slave:
    image: redis:7.4.0
    container_name: beastz_redis_slave
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: /bin/sh -c "redis-server --slaveof beastz_redis_master 6379 --masterauth $${REDIS_PASSWORD} --requirepass $${REDIS_PASSWORD}"
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli -h beastz_redis_slave -a $$REDIS_PASSWORD ping || exit 1']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '33003:6379'
    depends_on:
      beastz_redis_master:
        condition: service_healthy
    volumes:
      - beastz_redis_slave_data:/data
