# https://github.com/prisma/prisma/issues/10204
# https://stackoverflow.com/questions/72004347/github-actions-build-docker-image-with-a-secret-json-file-and-env-file

on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    environment: Prod
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: shut down the image
        run: docker compose down
      - name: remove dangling images
        run: docker image prune --all --force
      - name: rebuild the image
        run: docker compose build --no-cache
      - name: run the image
        run: docker compose up -d
    env:
      DEBUG: ${{vars.DEBUG}}
      PORT: ${{vars.PORT}}
      PRISMA_ENGINE_PROTOCOL: ${{vars.PRISMA_ENGINE_PROTOCOL}}
      MAX_FEEDBACK_PER_DAY_COUNT: ${{vars.MAX_FEEDBACK_PER_DAY_COUNT}}
      FRONTEND_URL: ${{vars.FRONTEND_URL}}
      FRONTEND_DOCUMENT_URL: ${{vars.FRONTEND_DOCUMENT_URL}}
      BACKEND_URL: ${{vars.BACKEND_URL}}
      ENABLE_SESSION_ACCESS_JWT_ENCRYPTION: ${{vars.ENABLE_SESSION_ACCESS_JWT_ENCRYPTION}}
      ADMIN_BASIC_PASSWORD: ${{vars.ADMIN_BASIC_PASSWORD}}
      ENABLE_MAIL_SANDBOX: ${{vars.ENABLE_MAIL_SANDBOX}}
      DATABASE_LOG_QUERY: ${{vars.DATABASE_LOG_QUERY}}
      DATABASE_URL: ${{vars.DATABASE_URL}}
      REDIS_URL: ${{vars.REDIS_URL}}
      MAIL_URL: ${{vars.MAIL_URL}}
      MAIL_USERNAME: ${{vars.MAIL_USERNAME}}
      MAIL_FROM: ${{vars.MAIL_FROM}}
      MAIL_PASSWORD: ${{vars.MAIL_PASSWORD}}
      COOKIE_SECRET: ${{vars.COOKIE_SECRET}}
      COOKIE_DOMAIN: ${{vars.COOKIE_DOMAIN}}
      ACCESS_TOKEN_EXPIRATION_IN_SEC: ${{vars.ACCESS_TOKEN_EXPIRATION_IN_SEC}}
      REFRESH_TOKEN_EXPIRATION_IN_SEC: ${{vars.REFRESH_TOKEN_EXPIRATION_IN_SEC}}
      RECOVER_PASSWORD_REQUEST_TIMEOUT_IN_SEC: ${{vars.RECOVER_PASSWORD_REQUEST_TIMEOUT_IN_SEC}}
      RESET_PASSWORD_REQUEST_TIMEOUT_IN_SEC: ${{vars.RESET_PASSWORD_REQUEST_TIMEOUT_IN_SEC}}
      ACCOUNT_VERIFICATION_TOKEN_EXPIRATION_IN_SEC: ${{vars.ACCOUNT_VERIFICATION_TOKEN_EXPIRATION_IN_SEC}}
      ACCESS_TOKEN_SECRET: ${{vars.ACCESS_TOKEN_SECRET}}
      REFRESH_TOKEN_SECRET: ${{vars.REFRESH_TOKEN_SECRET}}
      SESSION_JWT_ENCRYPTION_KEY: ${{vars.SESSION_JWT_ENCRYPTION_KEY}}
      ACCOUNT_VERIFY_TOKEN_SECRET: ${{vars.ACCOUNT_VERIFY_TOKEN_SECRET}}
      RECOVER_PASSWORD_TOKEN_SECRET: ${{vars.RECOVER_PASSWORD_TOKEN_SECRET}}
      RESET_PASSWORD_TOKEN_SECRET: ${{vars.RESET_PASSWORD_TOKEN_SECRET}}
      POSTGRES_PASSWORD: ${{vars.POSTGRES_PASSWORD}}
      POSTGRES_USERNAME: ${{vars.POSTGRES_USERNAME}}
      POSTGRES_DB: ${{vars.POSTGRES_DB}}
